version: '3.9'

services:
  caddy:
    image: caddy:2.7.4-alpine
    restart: unless-stopped
    container_name: sp-caddy
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    expose:
      - 9000
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./api/public:/www/app/public
      - ./data/caddy/data:/data
      - ./data/caddy/config:/config
    depends_on:
      front:
        condition: service_healthy
      php:
        condition: service_healthy
    networks:
      default:
        aliases:
          - api

  front:
    image: oven/bun:1.0-alpine
    working_dir: /home/bun/app
    container_name: sp-front
    user: bun
    entrypoint: [ "./scripts/bun.sh" ]
    volumes:
      - ./front:/home/bun/app
    stdin_open: true
    tty: true
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/api/healthz || exit 1
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 60s

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: unless-stopped
    container_name: sp-php
    volumes:
      - ./api:/www/app
      - ./docker/php/overrides.ini:/usr/local/etc/php/conf.d/overrides.ini
      - ./docker/php/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "php", "-v" ]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 60s

  mariadb:
    image: mariadb:11.1.2
    restart: unless-stopped
    container_name: sp-mariadb
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD:?err}"
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 60s

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    container_name: sp-phpmyadmin
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 512M
      MAX_EXECUTION_TIME: 300

  mailcatcher:
    image: schickling/mailcatcher:latest
    container_name: sp-mailcatcher

  rabbitmq:
    image: rabbitmq:management-alpine
    restart: unless-stopped
    container_name: sp-rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 60s
