api_platform:
    title: Symmetrical Potato API
    version: 1.0.0
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
    formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']

when@prod:
    api_platform:
        enable_docs: false
        enable_entrypoint: false
        enable_swagger: false
        enable_swagger_ui: false
        formats:
            jsonld:
                mime_types: ['application/ld+json']
            json:
                mime_types: ['application/json']
