api_platform:
    title: Symmetrical Potato API
    version: 1.0.0
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
        # Disable operations (only use GraphQL) by default
        item_operations: []
        collection_operations: []
    formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
        graphql:
            mime_types: ['application/graphql']
        html:
            mime_types: ['text/html']
    graphql:
        graphql_playground:
            enabled: false

when@prod:
    api_platform:
        enable_docs: false
        enable_entrypoint: false
        enable_swagger: false
        enable_swagger_ui: false
        formats:
            jsonld:
                mime_types: ['application/ld+json']
            json:
                mime_types: ['application/json']
            graphql:
                mime_types: ['application/graphql']
        graphql:
            graphiql:
                enabled: false
