framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: '%env(MAILER_NOREPLY_EMAIL)%'
        headers:
            from: '%env(MAILER_NOREPLY_NAME)% <%env(MAILER_NOREPLY_EMAIL)%>'
