---
- name: Create .env file Compose
  ansible.builtin.copy:
    dest: ./app/.env
    force: true
    mode: "0660"
    content: |
      MARIADB_USER={{ mariadb_user }}
      MARIADB_PASSWORD_HASH={{ mariadb_password_hash }}
      RABBITMQ_DEFAULT_USER={{ rabbitmq_default_user }}
      RABBITMQ_DEFAULT_PASS={{ rabbitmq_default_pass }}

- name: Create .env file Front
  ansible.builtin.copy:
    dest: ./app/front/.env
    force: true
    mode: "0660"
    content: |
      API_HOST={{ api_host }}
      API_GRAPHQL_ENDPOINT={{ api_graphql_endpoint }}
      NEXT_PUBLIC_SENTRY_DSN={{ next_public_sentry_dsn }}

- name: Create .env.prod file API
  ansible.builtin.copy:
    dest: ./app/api/.env.prod
    force: true
    mode: "0660"
    content: |
      APP_ENV={{ app_env }}
      APP_SECRET={{ app_secret }}
      APP_DEBUG={{ app_debug }}
      DATABASE_URL={{ database_url }}
      MAILER_DSN={{ mailer_dsn }}
      MAILER_NOREPLY_EMAIL={{ mailer_noreply_email }}
      MAILER_NOREPLY_NAME={{ mailer_noreply_name }}
      MESSENGER_TRANSPORT_DSN={{ messenger_transport_dsn }}
      CORS_ALLOW_ORIGIN={{ cors_allow_origin }}
      SENTRY_DSN={{ sentry_dsn }}
