---
- name: Install pip3
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install docker & docker-compose module
  ansible.builtin.pip:
    name:
      - docker
      - docker-compose
