---
- hosts: prod
  name: Install docker & docker-compose for Python
  tasks:
    - name: Install pip3
      ansible.builtin.apt:
        name: python3-pip
        state: present

    - name: Install docker & docker-compose Module for Python
      ansible.builtin.pip:
        name:
          - docker
          - docker-compose
