name: Deploy on VPS

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - name: webfactory/ssh-agent
      #   uses: webfactory/ssh-agent@v0.8.0
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Deploy on vps
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy-vps.yml
          directory: ./ansible
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          vault_password: ${{ secrets.VAULT_PASSWORD }}
          inventory: |
            [prod]
            ${{ secrets.VPS_HOST }} ansible_port=${{ secrets.VPS_PORT }} ansible_user=${{ secrets.VPS_USERNAME }}

            [prod:vars]
            ansible_python_interpreter=/usr/bin/python3
            