name: Publish Front

on:
  workflow_run:
    workflows: [Linting Front]
    types: [completed]
    branches: ["master"]

  push:
    branches:
      - master

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push-front:
    name: Push Docker image Front

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.26

      - name: Caching dependencies
        uses: actions/cache@v3
        id: cache-modules
        with:
          path: ./front/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}-node-modules

      - name: Cache CSS build
        uses: actions/cache@v3
        id: cache-css
        with:
          path: ./front/app/styles
          key: ${{ runner.os }}-remix-css-${{ hashFiles('front/tailwind.config.ts', 'front/styles/**/*.css', 'front/styles/**/*.scss') }}

      - name: Cache translations build
        uses: actions/cache@v3
        id: cache-translations
        with:
          path: ./front/public/locales
          key: ${{ runner.os }}-remix-translations-${{ hashFiles('front/locales/**/*') }}

      - name: Cache client build
        uses: actions/cache@v3
        id: cache-client
        with:
          path: ./front/public/build
          key: ${{ runner.os }}-remix-client-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('front/**/*.js', 'front/**/*.jsx', 'front/**/*.ts', 'front/**/*.tsx', 'front/**/*.css', 'front/**/*.scss', 'front/**/*.json', '!front/public/build/**', '!front/build/**') }}

      - name: Cache server build
        uses: actions/cache@v3
        id: cache-server
        with:
          path: ./front/build
          key: ${{ runner.os }}-remix-server-${{ hashFiles('front/**/bun.lockb') }}-${{ hashFiles('front/**/*.js', 'front/**/*.jsx', 'front/**/*.ts', 'front/**/*.tsx', 'front/**/*.css', 'front/**/*.scss', 'front/**/*.json', '!front/public/build/**', '!front/build/**') }}

      - name: Install dependencies
        if: steps.cache-modules.outputs.cache-hit != 'true'
        working-directory: ./front
        run: bun install --frozen-lockfile

      - name: Build CSS
        if: steps.cache-css.outputs.cache-hit != 'true'
        working-directory: ./front
        run: bun run build:css

      - name: Build translations
        if: steps.cache-translations.outputs.cache-hit != 'true'
        working-directory: ./front
        run: bun run build:translations

      - name: Front building phase
        if: steps.cache-client.outputs.cache-hit != 'true' || steps.cache-server.outputs.cache-hit != 'true' || steps.cache-css.outputs.cache-hit != 'true'
        working-directory: ./front
        run: bun run build:remix

      - name: Server building phase
        working-directory: ./front
        run: bun run build:server

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./front
          file: docker/prod/node/Dockerfile

          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: spacelocust/sp-front:latest

          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
