name: Linting Front

on:
  push:
    branches:
      - '**'
    paths:
      - "front/**"
      - ".github/workflows/docker-front.yml"
      - "docker/prod/node/**"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-front:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.2

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: ./front/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}

      - name: Cache CSS build
        uses: actions/cache@v3
        id: cache-css
        with:
          path: ./front/app/styles
          key: ${{ runner.os }}-remix-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('tailwind.config.ts', '**/*.css', '**/*.scss') }}

      - name: Cache client build
        uses: actions/cache@v3
        with:
          path: ./front/public/build
          key: ${{ runner.os }}-remix-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx', '**/*.css', '**/*.scss', '**/*.json') }}

      - name: Cache server build
        uses: actions/cache@v3
        with:
          path: ./front/build
          key: ${{ runner.os }}-remix-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx', '**/*.css', '**/*.scss', '**/*.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./front
        run: bun install --frozen-lockfile

      - name: Build CSS
        if: steps.cache-css.outputs.cache-hit != 'true'
        working-directory: ./front
        run: bun run build:css

      - name: Run linter
        working-directory: ./front
        run: bun run lint

      - name: Check building phase
        working-directory: ./front
        run: bun run build:remix
