name: Linting Front

on:
  push:
    branches:
      - '**'
    paths:
      - "front/**.ts"


jobs:
  lint-front:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.2

      - name: Install dependencies
        working-directory: ./front
        run: bun install --frozen-lockfile

      - name: Run linter
        working-directory: ./front
        run: bun run lint
