name: Linting API

on:
  push:
    branches:
      - '**'
    paths:
      - "api/**"
      - ".github/workflows/docker-api.yml"
      - ".github/workflows/lint-api.yml"
      - "docker/prod/php/**"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Validate composer.json and composer.lock
        working-directory: ./api
        run: composer validate --no-check-all --strict --no-check-publish

      - name: Install dependencies
        working-directory: ./api
        run: composer install

      - name: Run linter
        working-directory: ./api
        run: ./vendor/bin/php-cs-fixer fix src -v --dry-run

      - name: Run PHPStan
        working-directory: ./api
        run: ./vendor/bin/phpstan analyse
