name: Linting Front

on:
  push:
    branches:
      - '**'
    paths:
      - "front/**"
      - ".github/workflows/docker-front.yml"
      - "docker/prod/node/**"

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-front:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.2

      - name: Caching dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: ./front/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}

      - name: Caching build
        uses: actions/cache@v3
        with:
          path: ./front/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./front
        run: bun install --frozen-lockfile

      - name: Run linter
        working-directory: ./front
        run: bun run lint

      - name: Check building phase
        working-directory: ./front
        run: bun run build
