name: Linting API

on:
  push:
    branches:
      - '**'
    paths:
      - "api/**"
      - ".github/workflows/docker-api.yml"
      - "docker/prod/php/**"

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Caching dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: ./api/vendor
          key: ${{ runner.os }}-${{ hashFiles('**/composer.*') }}

      - name: Validate composer.json and composer.lock
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./api
        run: composer validate --no-check-all --strict --no-check-publish

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./api
        run: composer install

      - name: Run linter
        working-directory: ./api
        run: ./vendor/bin/php-cs-fixer fix src -v --dry-run
