name: Linting Front

on:
  push:
    branches:
      - '**'
    paths:
      - "front/**"
      - ".github/workflows/docker-front.yml"
      - ".github/workflows/lint-front.yml"
      - "docker/prod/node/**"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-front:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.2

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: ./front/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}

      - name: Cache CSS build
        uses: actions/cache@v3
        id: cache-css
        with:
          path: ./front/app/styles
          key: ${{ runner.os }}-remix-css-${{ hashFiles('front/tailwind.config.ts', 'front/styles/**/*.css', 'front/styles/**/*.scss') }}

      - name: Cache client build
        uses: actions/cache@v3
        id: cache-client
        with:
          path: ./front/public/build
          key: ${{ runner.os }}-remix-client-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('front/**/*.js', 'front/**/*.jsx', 'front/**/*.ts', 'front/**/*.tsx', 'front/**/*.css', 'front/**/*.scss', 'front/**/*.json', '!front/public/build/**', '!front/build/**') }}

      - name: Cache server build
        uses: actions/cache@v3
        id: cache-server
        with:
          path: ./front/build
          key: ${{ runner.os }}-remix-server-${{ hashFiles('front/**/bun.lockb') }}-${{ hashFiles('front/**/*.js', 'front/**/*.jsx', 'front/**/*.ts', 'front/**/*.tsx', 'front/**/*.css', 'front/**/*.scss', 'front/**/*.json', '!front/public/build/**', '!front/build/**') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./front
        run: bun install --frozen-lockfile

      - name: Build CSS
        if: steps.cache-css.outputs.cache-hit != 'true'
        working-directory: ./front
        run: bun run build:css

      - name: Run linter
        working-directory: ./front
        run: bun run lint

      - name: Check building phase
        if: steps.cache-client.outputs.cache-hit != 'true' || steps.cache-server.outputs.cache-hit != 'true' || steps.cache-css.outputs.cache-hit != 'true'
        working-directory: ./front
        run: bun run build:remix
