name: Testing API

on:
  push:
    branches:
      - '**'
    paths:
      - "api/**"
      - ".github/workflows/docker-api.yml"
      - ".github/workflows/test-api.yml"
      - "docker/prod/php/**"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-api:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:11.1.2
        env:
          MARIADB_ROOT_PASSWORD: root
        ports:
          - 3306:3306

      mailcatcher:
        image: schickling/mailcatcher:latest
        ports:
          - 1025:1025

      rabbitmq:
        image: rabbitmq:management-alpine
        ports:
          - 5672:5672

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: amqp, intl, pdo_mysql, pcntl

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: ./api/vendor
          key: ${{ runner.os }}-${{ hashFiles('**/composer.*') }}

      - name: Create .env.local
        uses: "DamianReeves/write-file-action@master"
        with:
          path: "./api/.env.local"
          write-mode: overwrite
          contents: |
            APP_ENV=test
            DATABASE_URL="mysql://root:root@127.0.0.1:${{ job.services.mariadb.ports[3306] }}/test?serverVersion=11.1.2-MariaDB-1&charset=utf8mb4"
            MAILER_DSN="smtp://127.0.0.1:${{ job.services.rabbitmq.ports[5672] }}"
            MESSENGER_TRANSPORT_DSN="amqp://guest:guest@127.0.0.1:${{ job.services.rabbitmq.ports[5672] }}/%2f/messages"

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./api
        run: composer install --prefer-dist --no-progress --no-suggest --ansi

      - name: Run tests
        working-directory: ./api
        run: php bin/phpunit

      - name: Validate Doctrine schema
        working-directory: ./api
        run: php bin/console doctrine:schema:validate --skip-sync
