name: Testing API

on:
  push:
    branches:
      - '**'
    paths:
      - "api/**"
      - ".github/workflows/docker-api.yml"
      - ".github/workflows/test-api.yml"
      - "docker/prod/php/**"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-api:
    runs-on: ubuntu-latest

    container: ubuntu:latest

    services:
      mariadb:
        image: mariadb:11.1.2
        env:
          MARIADB_ROOT_PASSWORD: root

      mailcatcher:
        image: schickling/mailcatcher:latest

      rabbitmq:
        image: rabbitmq:management-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: amqp, intl, pdo_mysql, pcntl

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: ./vendor
          key: ${{ runner.os }}-${{ hashFiles('**/composer.*') }}

      - name: Copy .env.ci to .env.local
        run: cp ./api/.env.ci ./api/.env.local

      - name: Install dependencies
        working-directory: ./api
        if: steps.cache.outputs.cache-hit != 'true'
        run: composer install

      - name: Run tests
        working-directory: ./api
        run: php bin/phpunit

      - name: Validate Doctrine schema
        working-directory: ./api
        run: php bin/console doctrine:schema:validate --skip-sync
