name: Workflow Notify

on:
  workflow_run:
    workflows:
      - "Testing API"
      - "Testing E2E"
      - "Linting Front"
      - "Linting API"
      - "Publish Front"
      - "Publish API"
      - "Deploy on VPS"
      - "Execute scheduled tasks"
    types: [completed]

jobs:
  on-success:
    name: Notify successfull workflow run

    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: 0x00ff00
          status: "success"
          content: "Listen up, this is a workflow run report! Workflow \"${{ github.event.workflow_run.name }}\" has been robbed successfully."
          title: "Workflow Run"
          description: |
            # Workflow ${{ github.event.workflow_run.name }} status report

            **Triggering Actor:** ${{ github.event.workflow_run.triggering_actor.login }}
            **Run Number:** ${{ github.event.workflow_run.run_number }}
            **Total Attempts:** ${{ github.event.workflow_run.run_attempt }}
          image: ${{ github.event.workflow_run.triggering_actor.avatar_url }}
          url: ${{ github.event.workflow_run.html_url }}

  on-failure:
    name: Notify failed workflow run

    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    steps:
      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: 0xff0000
          status: "failure"
          content: "Workflow run report! Workflow \"${{ github.event.workflow_run.name }}\" is now in custody..."
          title: "Workflow Run"
          description: |
            # Workflow ${{ github.event.workflow_run.name }} status report

            **Triggering Actor:** ${{ github.event.workflow_run.triggering_actor.login }}
            **Run Number:** ${{ github.event.workflow_run.run_number }}
            **Total Attempts:** ${{ github.event.workflow_run.run_attempt }}
          image: ${{ github.event.workflow_run.triggering_actor.avatar_url }}
          url: ${{ github.event.workflow_run.html_url }}
